/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#594400",
        "tertiary-fixed-dim": "#adc7ff",
        "secondary-fixed-dim": "#f6bf00",
        "primary-fixed-dim": "#ffb3ac",
        "on-tertiary": "#002e68",
        "surface-container": "#201f22",
        "primary": "#ffb3ac",
        "error": "#ffb4ab",
        "surface-container-lowest": "#0e0e10",
        "surface-container-high": "#2a2a2c",
        "surface-bright": "#39393b",
        "primary-container": "#d32f2f",
        "tertiary-container": "#006ce1",
        "surface-container-highest": "#353437",
        "on-background": "#e5e1e4",
        "primary-fixed": "#ffdad6",
        "on-secondary": "#3e2e00",
        "inverse-surface": "#e5e1e4",
        "surface-container-low": "#1c1b1d",
        "background": "#131315",
        "on-secondary-container": "#6c5200",
        "outline": "#ab8985",
        "on-error-container": "#ffdad6",
        "outline-variant": "#5b403d",
        "inverse-on-surface": "#313032",
        "inverse-primary": "#ba1a20",
        "on-tertiary-container": "#f3f4ff",
        "on-primary": "#680008",
        "on-error": "#690005",
        "surface-variant": "#353437",
        "surface-tint": "#ffb3ac",
        "secondary-container": "#fdc400",
        "on-surface-variant": "#e4beba",
        "tertiary": "#adc7ff",
        "on-primary-fixed": "#410003",
        "on-primary-container": "#fff2f0",
        "tertiary-fixed": "#d8e2ff",
        "surface": "#131315",
        "on-tertiary-fixed-variant": "#004493",
        "secondary-fixed": "#ffdf96",
        "on-tertiary-fixed": "#001a41",
        "on-secondary-fixed": "#251a00",
        "error-container": "#93000a",
        "on-primary-fixed-variant": "#930010",
        "secondary": "#ffe6ae",
        "surface-dim": "#131315",
        "on-surface": "#e5e1e4"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"],
        "manrope": ["Manrope"],
        "inter": ["Inter"]
      },
      borderRadius: { "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px" },
    },
  },
  plugins: [],
}
